name: SkyBlock
description: Plugin for SkyBlock Server
author: LyFlow
main: net.quillcraft.skyblock.SkyBlock
api-version: 1.19
version: 1.0.0-beta

commands:
  island:
    usage: §c/island <create/sell/tp/list/config> or /island <invite/accept/kick/leave> <player> or /island <set> <owner> <player> or /island <set> <spawn>
    description: command to manipulate your island
    aliases: is

  visit:
    usage: §c/visit <player>
    description: command to visit other island
    aliases: v

  lobby:
    usage: §c/lobby
    description: command to return to the lobby
    aliases: [ spawn, hub ]

  shop:
    usage: §c/shop
    description: command to access to the shop
    aliases: s

  money:
    usage: §c/money or /money <send> <player>
    description: command to see your money or send money to any player
    aliases: m

  challenge:
    usage: §c/challenge
    description: command to access to the challenges
    aliases: c